# Generated by Django 5.1.3 on 2025-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_rename_user_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('post', models.CharField(max_length=256)),
            ],
        ),
    ]
